### ISSUE TITLE
Usage of 'Math' Library?

### ISSUE THREAD

**Issue by Aryan9592** [chromatic-protocol/contracts#649]
I was just digging down the codebase and noticed something in file [MarketLiquidityFacet.sol](https://github.com/chromatic-protocol/contracts/blob/main/contracts/core/facets/market/MarketLiquidityFacet.sol). Everything seems okay, But in starting of the contract file, a code line states -> `using Math for uint256`.
Now the thing is, this solidity file is using the pragma version `>=0.8.0 <0.9.0`. Usually, `Math` library is used for safeguarding our code from underflow/overflow checks but here `v0.8` is already equipped with `underflow/overflow` checks. Moreover, I haven't seen any method of 'Math' library, like -> sub, add, mul etc..
Just want to know, do this implementation of 'Math' library really meant something here or not?

**Comment by not-thing** [comment]
yes you're correct. It seems just a mistake and already fixed when merging your PR #648  
  
https://github.com/chromatic-protocol/contracts/pull/648/commits/0ad6badde84ace59f2ea14fd7594f0469bce338e

Thank you for your interest

**Comment by Aryan9592** [comment]
Yea I know, but is that fix applied to all files in this codebase, or just to that one?

**Comment by not-thing** [comment]
I'll investigate other places such a  mistake in Monday. thank you

**Comment by Aryan9592** [comment]
Hmm, I guess just to the file listed in #648

**Comment by Aryan9592** [comment]
> I'll investigate other places such a mistake in Monday. thank you

May I try? you can review that later

**Comment by not-thing** [comment]
> > I'll investigate other places such a mistake in Monday. thank you
> 
> May I try? you can review that later

Why not!

**Comment by Aryan9592** [comment]
Well, there's also a need to look for unused imports...like this one
File reference -> [here](https://github.com/chromatic-protocol/contracts/blob/main/contracts/oracle/PythFeedOracle.sol)

![Screenshot (51)](https://github.com/chromatic-protocol/contracts/assets/88618913/10842bc4-814c-4146-bca0-35a979d7cccc)
